name: Check PR for each commit
on:
    pull_request:
        branches:
            - 'development'
jobs:
    prcheck:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4
            - name: Install Dotnet
              uses: actions/setup-dotnet@v4
              with:
                dotnet-version: '8.0.x'
            - name: Restore Dependencies
              run: dotnet restore
            - name: Build project
              run: dotnet build --no-restore
            - name: Test project
              run: dotnet test --no-restore 
              